In [32]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [33]:
df_car = pd.read_csv(r"C:\Users\ASUS\Desktop\Projects\acko_insurance_project\data\model_data\Quotation\acko_car_quotation.csv")
df_bike = pd.read_csv(r"C:\Users\ASUS\Desktop\Projects\acko_insurance_project\data\model_data\Quotation\acko_bike_quotation.csv")
df_health = pd.read_csv(r"C:\Users\ASUS\Desktop\Projects\acko_insurance_project\data\model_data\Quotation\acko_health_quotation.csv")

In [34]:
df_car

,record_id,customer_age,city,state,city_tier,city_risk_score,vehicle_make,vehicle_model,variant,segment,...,policy_type,previous_insurer,num_addons,addons_list,od_premium_before_ncb,ncb_discount_amount,tp_premium,addon_premium,gst_amount,annual_premium
0,d96cac39,26,Kolkata,West Bengal,1,1.40,Honda,Amaze,Deluxe,sedan,...,Third Party,Tata AIG,0,NaN,13543.01,6771.51,3416,0.00,614.88,4212
1,8a5e47cd,59,Panaji,Goa,3,0.95,Mercedes-Benz,A-Class Limousine,Sport,sedan,...,Comprehensive,Acko,3,"Personal Accident Cover, Return to Invoice, Ke...",133631.52,66815.76,3416,3192.95,14419.13,95457
2,653b7fa5,40,Bhopal,Madhya Pradesh,2,1.12,Nissan,Magnite,Turbo,suv,...,Third Party,Reliance General,4,"Personal Accident Cover, Roadside Assistance, ...",11130.53,2782.63,2094,7474.75,376.92,2385
3,b3ec92ca,32,Madurai,Tamil Nadu,2,1.10,Ford,Aspire,Long Range,sedan,...,Third Party,Tata AIG,1,Return to Invoice,10674.04,2668.51,3416,1076.51,614.88,4178
4,43ef7ada,61,Thiruvananthapuram,Kerala,3,1.00,Ford,Aspire,Deluxe,sedan,...,Comprehensive,Bajaj Allianz,1,Consumables Cover,9590.42,4795.21,3416,1173.35,1858.14,12434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,3651321b,57,Mysuru,Karnataka,2,1.08,Skoda,Kushaq,Top,suv,...,Third Party,Tata AIG,0,NaN,46834.02,0.00,2094,0.00,376.92,2378
199996,6a110559,68,Jammu,Jammu & Kashmir,3,0.92,Skoda,Superb,CVT,sedan,...,Comprehensive,Reliance General,1,Tyre Protection,87244.09,43622.04,7897,1239.87,11309.98,73339
199997,3ea5159a,22,Warangal,Telangana,2,1.05,Kia,Sonet,CVT,suv,...,Comprehensive,Acko,2,"Personal Accident Cover, Consumables Cover",14616.15,5115.65,2094,2968.08,3211.11,21577
199998,632b2cec,61,Mangalore,Karnataka,3,0.95,Jeep,Meridian,DCT,suv,...,Comprehensive,NaN,1,Consumables Cover,50271.87,10054.37,7897,1503.32,10620.63,70150
199999,d8a41388,25,Kakinada,Andhra Pradesh,3,0.88,Mahindra,TUV300,AMT,suv,...,Third Party,ICICI Lombard,1,No Claim Bonus Protection,14750.98,0.00,3416,1464.50,614.88,4031

In [35]:
df_car.describe()

,customer_age,city_tier,city_risk_score,manufacturing_year,vehicle_age_years,engine_cc,idv,ncb_percent,claim_history_count,num_addons,od_premium_before_ncb,ncb_discount_amount,tp_premium,addon_premium,gst_amount,annual_premium
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,2.000000e+05,200000.000000,200000.000000,200000.000000,2.000000e+05,200000.000000,200000.000000,200000.000000,200000.000000,2.000000e+05
mean,46.524740,2.435315,1.031174,2014.507050,10.492950,1312.327660,1.513422e+06,29.180800,0.882015,1.449935,6.334452e+04,18484.230142,4172.324945,2390.242746,7923.206599,5.193187e+04
std,16.748066,0.617865,0.160228,5.762987,5.762987,776.538865,2.149447e+06,16.681436,1.092863,1.161572,8.748986e+04,31111.599229,2391.727211,2119.675971,12438.922308,8.155203e+04
min,18.000000,1.000000,0.820000,2005.000000,1.000000,0.000000,9.469100e+04,0.000000,0.000000,0.000000,3.219370e+03,0.000000,2094.000000,0.000000,376.920000,2.347000e+03
25%,32.000000,2.000000,0.900000,2010.000000,5.000000,999.000000,3.414438e+05,20.000000,0.000000,0.000000,1.546649e+04,3110.760000,2094.000000,0.000000,1563.610000,1.024800e+04
50%,47.000000,3.000000,1.000000,2014.000000,11.000000,1199.000000,6.870595e+05,35.000000,0.000000,1.000000,2.862012e+04,7501.930000,3416.000000,2033.225000,3610.190000,2.366000e+04
75%,61.000000,3.000000,1.120000,2020.000000,15.000000,1956.000000,1.775388e+06,45.000000,2.000000,2.000000,7.716096e+04,20809.437500,7897.000000,3732.000000,8923.302500,5.840250e+04
max,75.000000,3.000000,1.500000,2024.000000,20.000000,3346.000000,2.373989e+07,50.000000,4.000000,4.000000,1.229050e+06,525316.160000,7897.000000,9999.010000,244980.860000,1.607449e+06

In [36]:
df_car.duplicated().sum()

np.int64(0)

In [37]:
df_car.isnull().sum()

record_id                    0
customer_age                 0
city                         0
state                        0
city_tier                    0
city_risk_score              0
vehicle_make                 0
vehicle_model                0
variant                      0
segment                      0
fuel_type                    0
colour                       0
manufacturing_year           0
vehicle_age_years            0
engine_cc                    0
idv                          0
ncb_percent                  0
claim_history_count          0
policy_type                  0
previous_insurer         22121
num_addons                   0
addons_list              50140
od_premium_before_ncb        0
ncb_discount_amount          0
tp_premium                   0
addon_premium                0
gst_amount                   0
annual_premium               0
dtype: int64

In [38]:
df_car["previous_insurer"]=df_car["previous_insurer"].fillna("unknown")

In [39]:
(df_car["num_addons"] == 0).sum()

np.int64(50140)

In [40]:
df_car['addons_list'] = df_car['addons_list'].fillna('')

In [41]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

# 1. Clean the text and convert comma-separated strings into clean Python lists
def clean_addon_string(text):
    # Handle NaN or empty string inputs gracefully
    if pd.isna(text) or text == '':
        return []
    # Split by comma and strip out accidental whitespace around names
    return [addon.strip() for addon in text.split(',') if addon.strip()]

# Apply the text cleaning function to your column
df_car['addons_list_clean'] = df_car['addons_list'].apply(clean_addon_string)

# 2. Initialize the MultiLabelBinarizer with Sparse Output enabled
# This completely prevents memory crashes by ignoring zero values
mlb = MultiLabelBinarizer(sparse_output=True)

# 3. Fit and transform the clean lists into a compressed matrix
X_addons_sparse = mlb.fit_transform(df_car['addons_list_clean'])

# 4. Verify your results
print(f"Compressed Sparse Matrix Shape: {X_addons_sparse.shape}")
print(f"Detected Unique Addon Columns: {mlb.classes_}")

Compressed Sparse Matrix Shape: (200000, 10)
Detected Unique Addon Columns: ['Consumables Cover' 'Engine Protection' 'Key Replacement'
 'No Claim Bonus Protection' 'Passenger Cover' 'Personal Accident Cover'
 'Return to Invoice' 'Roadside Assistance' 'Tyre Protection'
 'Zero Depreciation']

In [42]:
sample_df = pd.DataFrame(
    X_addons_sparse[:5].toarray(), 
    columns=mlb.classes_
)
sample_df

,Consumables Cover,Engine Protection,Key Replacement,No Claim Bonus Protection,Passenger Cover,Personal Accident Cover,Return to Invoice,Roadside Assistance,Tyre Protection,Zero Depreciation
0,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,1,1,0,0,0
2,0,0,1,1,0,1,0,1,0,0
3,0,0,0,0,0,0,1,0,0,0
4,1,0,0,0,0,0,0,0,0,0

In [43]:
# 1. Convert the sparse matrix into a standard DataFrame with proper column names
addons_df = pd.DataFrame.sparse.from_spmatrix(
    X_addons_sparse, 
    columns=[f"addon_{name.lower().replace(' ', '_')}" for name in mlb.classes_]
)

# 2. Reset indices to ensure perfect horizontal alignment
df_car = df_car.reset_index(drop=True)
addons_df = addons_df.reset_index(drop=True)

# 3. Glue them together side-by-side
df_car = pd.concat([df_car, addons_df], axis=1)

In [44]:
df_car.head()

,record_id,customer_age,city,state,city_tier,city_risk_score,vehicle_make,vehicle_model,variant,segment,...,addon_consumables_cover,addon_engine_protection,addon_key_replacement,addon_no_claim_bonus_protection,addon_passenger_cover,addon_personal_accident_cover,addon_return_to_invoice,addon_roadside_assistance,addon_tyre_protection,addon_zero_depreciation
0,d96cac39,26,Kolkata,West Bengal,1,1.40,Honda,Amaze,Deluxe,sedan,...,0,0,0,0,0,0,0,0,0,0
1,8a5e47cd,59,Panaji,Goa,3,0.95,Mercedes-Benz,A-Class Limousine,Sport,sedan,...,0,0,1,0,0,1,1,0,0,0
2,653b7fa5,40,Bhopal,Madhya Pradesh,2,1.12,Nissan,Magnite,Turbo,suv,...,0,0,1,1,0,1,0,1,0,0
3,b3ec92ca,32,Madurai,Tamil Nadu,2,1.10,Ford,Aspire,Long Range,sedan,...,0,0,0,0,0,0,1,0,0,0
4,43ef7ada,61,Thiruvananthapuram,Kerala,3,1.00,Ford,Aspire,Deluxe,sedan,...,1,0,0,0,0,0,0,0,0,0

In [45]:
df_car.dtypes

record_id                                       str
customer_age                                  int64
city                                            str
state                                           str
city_tier                                     int64
city_risk_score                             float64
vehicle_make                                    str
vehicle_model                                   str
variant                                         str
segment                                         str
fuel_type                                       str
colour                                          str
manufacturing_year                            int64
vehicle_age_years                             int64
engine_cc                                     int64
idv                                           int64
ncb_percent                                   int64
claim_history_count                           int64
policy_type                                     str
previous_insurer                                str
num_addons                                    int64
addons_list                                     str
od_premium_before_ncb                       float64
ncb_discount_amount                         float64
tp_premium                                    int64
addon_premium                               float64
gst_amount                                  float64
annual_premium                                int64
addons_list_clean                            object
addon_consumables_cover            Sparse[int64, 0]
addon_engine_protection            Sparse[int64, 0]
addon_key_replacement              Sparse[int64, 0]
addon_no_claim_bonus_protection    Sparse[int64, 0]
addon_passenger_cover              Sparse[int64, 0]
addon_personal_accident_cover      Sparse[int64, 0]
addon_return_to_invoice            Sparse[int64, 0]
addon_roadside_assistance          Sparse[int64, 0]
addon_tyre_protection              Sparse[int64, 0]
addon_zero_depreciation            Sparse[int64, 0]
dtype: object

In [46]:
drop_cols = [
    'record_id', 'annual_premium', 'addons_list', 'addons_list_clean',
    'od_premium_before_ncb', 'ncb_discount_amount', 'tp_premium', 
    'addon_premium', 'gst_amount'
]
x = df_car.drop(columns=drop_cols, errors='ignore')

In [47]:
x.columns

Index(['customer_age', 'city', 'state', 'city_tier', 'city_risk_score',
       'vehicle_make', 'vehicle_model', 'variant', 'segment', 'fuel_type',
       'colour', 'manufacturing_year', 'vehicle_age_years', 'engine_cc', 'idv',
       'ncb_percent', 'claim_history_count', 'policy_type', 'previous_insurer',
       'num_addons', 'addon_consumables_cover', 'addon_engine_protection',
       'addon_key_replacement', 'addon_no_claim_bonus_protection',
       'addon_passenger_cover', 'addon_personal_accident_cover',
       'addon_return_to_invoice', 'addon_roadside_assistance',
       'addon_tyre_protection', 'addon_zero_depreciation'],
      dtype='str')

In [48]:
numeric = [
    'customer_age', 'city_tier', 'city_risk_score', 'manufacturing_year', 
    'vehicle_age_years', 'engine_cc', 'idv', 'ncb_percent', 
    'claim_history_count', 'num_addons',
    'addon_consumables_cover', 'addon_engine_protection', 'addon_key_replacement', 
    'addon_no_claim_bonus_protection', 'addon_passenger_cover', 'addon_personal_accident_cover',
    'addon_return_to_invoice', 'addon_roadside_assistance', 'addon_tyre_protection', 
    'addon_zero_depreciation'
]

# 2. CORRECT CATEGORICAL LIST
category = [
    'vehicle_make', 'vehicle_model', 'variant', 'segment', 
    'fuel_type', 'colour', 'policy_type', 'previous_insurer', 
    'city', 'state'
]

In [49]:
numeric_corr = df_car[numeric].corrwith(df_car['annual_premium']).abs()

# Sort and display the results cleanly
numeric_ranking = pd.DataFrame({
    'Numeric Feature': numeric_corr.index,
    'Correlation Score': numeric_corr.values
}).sort_values(by='Correlation Score', ascending=False)

print("🏆 Numeric Columns Ranked by Relationship to Premium:")
print(numeric_ranking.to_string(index=False))

🏆 Numeric Columns Ranked by Relationship to Premium:
                Numeric Feature  Correlation Score
                            idv           0.753899
                      engine_cc           0.380667
              vehicle_age_years           0.154180
             manufacturing_year           0.154180
                    ncb_percent           0.128293
                city_risk_score           0.088304
                      city_tier           0.082747
            claim_history_count           0.052760
                     num_addons           0.020997
  addon_personal_accident_cover           0.011231
        addon_return_to_invoice           0.008972
addon_no_claim_bonus_protection           0.008812
          addon_key_replacement           0.008539
          addon_tyre_protection           0.007633
      addon_roadside_assistance           0.007504
        addon_consumables_cover           0.007091
        addon_engine_protection           0.003796
        addon_zero_depreciation           0.003568
                   customer_age           0.002727
          addon_passenger_cover           0.002128

In [50]:
from sklearn.feature_selection import mutual_info_regression

# 1. Temporarily fill missing text values for calculation
X_cat_temp = df_car[category].fillna('Unknown')

# 2. Convert text words into numerical codes so the MI algorithm can read them
for col in category:
    X_cat_temp[col] = X_cat_temp[col].astype('category').cat.codes

# 3. Calculate Mutual Information scores
mi_scores = mutual_info_regression(X_cat_temp, df_car['annual_premium'], random_state=42)

# 4. Sort and display the rankings
cat_ranking = pd.DataFrame({
    'Categorical Feature': category,
    'Mutual Info Score': mi_scores
}).sort_values(by='Mutual Info Score', ascending=False)

print("\n🏆 Categorical Columns Ranked by Relationship to Premium:")
print(cat_ranking.to_string(index=False))

🏆 Categorical Columns Ranked by Relationship to Premium:
Categorical Feature  Mutual Info Score
      vehicle_model           0.868020
        policy_type           0.525168
       vehicle_make           0.461779
            segment           0.137505
          fuel_type           0.069267
               city           0.008211
              state           0.004524
            variant           0.001557
             colour           0.000000
   previous_insurer           0.000000

In [51]:
num = [
    'customer_age', 'city_tier', 'city_risk_score', 'manufacturing_year', 
    'vehicle_age_years', 'engine_cc', 'idv', 'ncb_percent', 
    'claim_history_count', 'num_addons',
    'addon_consumables_cover', 'addon_engine_protection', 'addon_key_replacement', 
    'addon_no_claim_bonus_protection', 'addon_passenger_cover', 'addon_personal_accident_cover',
    'addon_return_to_invoice', 'addon_roadside_assistance', 'addon_tyre_protection', 
    'addon_zero_depreciation'
]

# 2. CORRECT CATEGORICAL LIST
cat = [
    'vehicle_make', 'vehicle_model', 'variant', 'segment', 
    'fuel_type','policy_type',
    'city', 'state'
]

In [52]:
X = df_car[num + cat]
Y = df_car['annual_premium']

In [53]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, TargetEncoder, StandardScaler,LabelEncoder,OrdinalEncoder
from xgboost import XGBRegressor

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [55]:
cat_low = ['segment', 'fuel_type', 'policy_type']
cat_high = ['city', 'state', 'vehicle_make', 'vehicle_model', 'variant']
base_numeric = ['customer_age', 'city_tier', 'city_risk_score', 'vehicle_age_years', 
                'engine_cc', 'idv', 'ncb_percent', 'claim_history_count', 'num_addons','manufacturing_year']

In [56]:
preprocessor = ColumnTransformer(
    transformers=[
        # Encode ALL text categories safely with zero memory overhead
        ('all_categorical_encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), 
         ['segment', 'fuel_type', 'policy_type', 'city', 'state', 'vehicle_make', 'vehicle_model', 'variant']),
        
        # Scale continuous numbers
        ('numerical_scaler', StandardScaler(), 
         ['customer_age', 'city_tier', 'city_risk_score', 'vehicle_age_years', 
          'engine_cc', 'idv', 'ncb_percent', 'claim_history_count', 'num_addons','manufacturing_year']),
    ],
    remainder='passthrough',
    sparse_threshold=0.0
)

In [57]:
X_train_final = preprocessor.fit_transform(X_train, y_train)
X_test_final = preprocessor.transform(X_test)

In [58]:
model = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    tree_method='hist', # Super-fast optimization for heavy datasets
    random_state=42,
    n_jobs=-1
)

model.fit(X_train_final, y_train)
print("🏆 Model training complete!")

🏆 Model training complete!

In [59]:
print(f"Final Model Train R² Score: {model.score(X_train_final, y_train):.4f}")
print(f"Final Model Test R² Score: {model.score(X_test_final, y_test):.4f}")

Final Model Train R² Score: 0.9972
Final Model Test R² Score: 0.9952

In [60]:
import joblib
import os

os.makedirs('model_artifacts', exist_ok=True)


joblib.dump(preprocessor, 'ml/saved_models/car_insurance_preprocessor.pkl')
joblib.dump(model, 'ml/saved_models/car_insurance_xgboost_model.pkl')

print("💾 Production files successfully saved in 'model_artifacts/' folder!")

💾 Production files successfully saved in 'model_artifacts/' folder!

In [3]:
df_bike

,record_id,customer_age,city,state,city_tier,city_risk_score,vehicle_make,vehicle_model,variant,segment,...,policy_type,usage_type,num_addons,addons_list,od_premium_before_ncb,ncb_discount_amount,tp_premium,addon_premium,gst_amount,annual_premium
0,c007100c,60,Rajahmundry,Andhra Pradesh,3,0.88,Royal Enfield,Bullet 500,STD,retro,...,Comprehensive,Personal,0,NaN,3861.87,0.00,2804,0.00,1295.85,8338
1,01557b26,21,Indore,Madhya Pradesh,2,1.15,Yamaha,Fascino 125,ABS,scooter,...,Third Party,Personal,0,NaN,1139.68,512.86,714,0.00,151.65,1035
2,656c8f49,19,Patna,Bihar,2,1.20,Suzuki,Gixxer 150,Drum,sport,...,Third Party,Personal,3,"Roadside Assistance, Consumables Cover, Return...",2464.40,862.54,1366,3317.48,290.14,1829
3,506ccfca,20,Muzaffarpur,Bihar,3,0.88,Bounce,Infinity E1,ABS,ev_scooter,...,Comprehensive,Personal,0,NaN,702.02,315.91,687,0.00,227.93,1536
4,3d46cd32,19,Karnal,Haryana,3,0.90,Honda,CB Hornet 2.0,Limited Edition,sport,...,Own Damage,Personal,0,NaN,2164.95,974.23,1366,0.00,252.91,1731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,3f453740,45,Ahmedabad,Gujarat,1,1.30,Ola Electric,S1 X,Disc,ev_scooter,...,Comprehensive,Personal,1,Zero Depreciation,1331.25,465.94,687,991.76,457.93,2852
149996,7afc65c4,20,Hisar,Haryana,3,0.90,Honda,CB Hornet 2.0,Limited Edition,sport,...,Comprehensive,Commercial,2,"Return to Invoice, Zero Depreciation",2550.70,0.00,1366,1711.77,1195.49,7783
149997,a4e45542,65,Moradabad,Uttar Pradesh,2,1.10,Royal Enfield,Thunderbird 350X,Sport,cruiser,...,Third Party,Personal,1,Return to Invoice,4617.64,0.00,1366,453.01,265.55,1687
149998,474628c4,63,Bengaluru,Karnataka,1,1.45,TVS,Apache RTR 160 4V,STD,sport,...,Comprehensive,Personal,2,"Return to Invoice, Consumables Cover",6151.40,0.00,1366,2015.13,1948.79,13367
149999,77a12382,29,Warangal,Telangana,2,1.05,Ampere,Magnus EX,Bluetooth,ev_scooter,...,Own Damage,Commercial,0,NaN,1685.66,337.13,687,0.00,242.73,1629

In [4]:
df_bike.describe()

,customer_age,city_tier,city_risk_score,manufacturing_year,vehicle_age_years,engine_cc,idv,ncb_percent,claim_history_count,num_addons,od_premium_before_ncb,ncb_discount_amount,tp_premium,addon_premium,gst_amount,annual_premium
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.500000e+05,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,41.495560,2.434287,1.031477,2014.499307,10.500693,215.089827,1.092865e+05,29.160267,0.671833,0.919227,5735.309428,1676.895140,1296.850427,687.122142,861.266757,5646.404507
std,13.849514,0.620251,0.160689,5.775248,5.775248,269.929363,1.832771e+05,16.671414,0.874306,0.924389,9828.518608,3453.377221,811.710032,768.923055,1331.826527,8736.957401
min,18.000000,1.000000,0.820000,2005.000000,1.000000,0.000000,1.500000e+04,0.000000,0.000000,0.000000,469.450000,0.000000,687.000000,0.000000,56.120000,538.000000
25%,30.000000,2.000000,0.900000,2009.000000,5.000000,0.000000,3.437800e+04,20.000000,0.000000,0.000000,1431.057500,303.592500,687.000000,0.000000,245.880000,1666.000000
50%,41.000000,3.000000,1.000000,2014.000000,11.000000,125.000000,5.633900e+04,25.000000,0.000000,1.000000,2469.465000,666.270000,714.000000,553.915000,504.720000,3263.000000
75%,54.000000,3.000000,1.120000,2020.000000,16.000000,312.000000,1.035392e+05,45.000000,1.000000,2.000000,5332.227500,1527.340000,1366.000000,1065.695000,870.900000,5711.000000
max,65.000000,3.000000,1.500000,2024.000000,20.000000,1833.000000,3.801389e+06,50.000000,3.000000,3.000000,260756.420000,91337.740000,2804.000000,3599.660000,37645.010000,252983.000000

In [5]:
df_bike.duplicated().sum()

np.int64(0)

In [6]:
df_bike.isnull().sum()

record_id                    0
customer_age                 0
city                         0
state                        0
city_tier                    0
city_risk_score              0
vehicle_make                 0
vehicle_model                0
variant                      0
segment                      0
fuel_type                    0
colour                       0
manufacturing_year           0
vehicle_age_years            0
engine_cc                    0
idv                          0
ncb_percent                  0
claim_history_count          0
policy_type                  0
usage_type                   0
num_addons                   0
addons_list              60173
od_premium_before_ncb        0
ncb_discount_amount          0
tp_premium                   0
addon_premium                0
gst_amount                   0
annual_premium               0
dtype: int64

In [7]:
df_bike.sample(10)

,record_id,customer_age,city,state,city_tier,city_risk_score,vehicle_make,vehicle_model,variant,segment,...,policy_type,usage_type,num_addons,addons_list,od_premium_before_ncb,ncb_discount_amount,tp_premium,addon_premium,gst_amount,annual_premium
19988,dff94686,35,Srinagar,Jammu & Kashmir,2,1.10,Hero MotoCorp,Glamour,Special Edition,commuter,...,Comprehensive,Personal,3,"Pillion Rider Cover, Engine Protection, Consum...",2330.22,582.56,714,2403.03,900.81,6062
141691,dc850f48,56,Ahmedabad,Gujarat,1,1.30,Hero MotoCorp,Xoom 125R,Deluxe,scooter,...,Comprehensive,Personal,2,"Pillion Rider Cover, Engine Protection",2638.35,659.59,714,2129.13,867.94,5721
108043,6a17029b,57,Bhubaneswar,Odisha,2,1.10,Suzuki,Gixxer 250,Double Disc,sport,...,Comprehensive,Commercial,1,Pillion Rider Cover,6876.16,3094.27,1366,1059.06,1117.25,7083
96207,cf900071,58,Tirunelveli,Tamil Nadu,3,0.90,Honda,Activa 6G,Double Disc,scooter,...,Comprehensive,Personal,1,Consumables Cover,1054.00,474.30,714,851.81,386.19,2443
117200,9a936210,58,Vizianagaram,Andhra Pradesh,3,0.88,Royal Enfield,Bullet 500,Limited Edition,retro,...,Comprehensive,Personal,2,"Engine Protection, Pillion Rider Cover",4672.22,2102.50,2804,937.54,1173.03,7824
106395,e14643a7,53,Muzaffarpur,Bihar,3,0.88,Bajaj,Pulsar F250,Special Edition,sport,...,Third Party,Personal,2,"Zero Depreciation, Engine Protection",2246.27,786.20,1366,1701.80,245.88,1651
32581,fa7bc268,22,Vellore,Tamil Nadu,3,0.92,Kawasaki,Ninja 400,Bluetooth,supersport,...,Comprehensive,Delivery,0,NaN,13849.27,3462.32,2804,0.00,2801.76,18894
96870,13f14eca,34,Guntur,Andhra Pradesh,2,1.05,Bounce,Infinity E1,DRL,ev_scooter,...,Third Party,Commercial,2,"Return to Invoice, Pillion Rider Cover",1251.12,563.00,687,1825.49,123.66,847
75765,9adeb4f9,32,Gorakhpur,Uttar Pradesh,2,1.10,TVS,Apache RTR 200 4V,Standard,sport,...,Third Party,Personal,0,NaN,2928.40,1464.20,1366,0.00,245.88,1646
137686,2d003992,37,Rajahmundry,Andhra Pradesh,3,0.88,Ola Electric,S1 X,STD,ev_scooter,...,Comprehensive,Delivery,0,NaN,1378.29,482.40,687,0.00,310.72,2042

In [8]:
df_bike['addons_list']=df_bike['addons_list'].fillna('Unknown')

In [9]:
df_bike.isnull().sum()

record_id                0
customer_age             0
city                     0
state                    0
city_tier                0
city_risk_score          0
vehicle_make             0
vehicle_model            0
variant                  0
segment                  0
fuel_type                0
colour                   0
manufacturing_year       0
vehicle_age_years        0
engine_cc                0
idv                      0
ncb_percent              0
claim_history_count      0
policy_type              0
usage_type               0
num_addons               0
addons_list              0
od_premium_before_ncb    0
ncb_discount_amount      0
tp_premium               0
addon_premium            0
gst_amount               0
annual_premium           0
dtype: int64

In [11]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

# 1. Clean the text and convert comma-separated strings into clean Python lists
def clean_addon_string2(text):
    # Handle NaN or empty string inputs gracefully
    if pd.isna(text) or text == '':
        return []
    # Split by comma and strip out accidental whitespace around names
    return [addon.strip() for addon in text.split(',') if addon.strip()]

# Apply the text cleaning function to your column
df_bike['addons_list_clean'] = df_bike['addons_list'].apply(clean_addon_string2)

# 2. Initialize the MultiLabelBinarizer with Sparse Output enabled
# This completely prevents memory crashes by ignoring zero values
mlb = MultiLabelBinarizer(sparse_output=True)

# 3. Fit and transform the clean lists into a compressed matrix
X_addons_bike_sparse = mlb.fit_transform(df_bike['addons_list_clean'])

# 4. Verify your results
print(f"Compressed Sparse Matrix Shape: {X_addons_bike_sparse.shape}")
print(f"Detected Unique Addon Columns: {mlb.classes_}")

Compressed Sparse Matrix Shape: (150000, 7)
Detected Unique Addon Columns: ['Consumables Cover' 'Engine Protection' 'Pillion Rider Cover'
 'Return to Invoice' 'Roadside Assistance' 'Unknown' 'Zero Depreciation']

In [12]:
addons_b_df = pd.DataFrame.sparse.from_spmatrix(
    X_addons_bike_sparse, 
    columns=[f"addon_{name.lower().replace(' ', '_')}" for name in mlb.classes_]
)

# 2. Reset indices to ensure perfect horizontal alignment
df_bike = df_bike.reset_index(drop=True)
addons_b_df = addons_b_df.reset_index(drop=True)

# 3. Glue them together side-by-side
bike = pd.concat([df_bike, addons_b_df], axis=1)

In [13]:
df_bike.head()

,record_id,customer_age,city,state,city_tier,city_risk_score,vehicle_make,vehicle_model,variant,segment,...,usage_type,num_addons,addons_list,od_premium_before_ncb,ncb_discount_amount,tp_premium,addon_premium,gst_amount,annual_premium,addons_list_clean
0,c007100c,60,Rajahmundry,Andhra Pradesh,3,0.88,Royal Enfield,Bullet 500,STD,retro,...,Personal,0,Unknown,3861.87,0.00,2804,0.00,1295.85,8338,[Unknown]
1,01557b26,21,Indore,Madhya Pradesh,2,1.15,Yamaha,Fascino 125,ABS,scooter,...,Personal,0,Unknown,1139.68,512.86,714,0.00,151.65,1035,[Unknown]
2,656c8f49,19,Patna,Bihar,2,1.20,Suzuki,Gixxer 150,Drum,sport,...,Personal,3,"Roadside Assistance, Consumables Cover, Return...",2464.40,862.54,1366,3317.48,290.14,1829,"[Roadside Assistance, Consumables Cover, Retur..."
3,506ccfca,20,Muzaffarpur,Bihar,3,0.88,Bounce,Infinity E1,ABS,ev_scooter,...,Personal,0,Unknown,702.02,315.91,687,0.00,227.93,1536,[Unknown]
4,3d46cd32,19,Karnal,Haryana,3,0.90,Honda,CB Hornet 2.0,Limited Edition,sport,...,Personal,0,Unknown,2164.95,974.23,1366,0.00,252.91,1731,[Unknown]

In [14]:
df_bike.dtypes

record_id                    str
customer_age               int64
city                         str
state                        str
city_tier                  int64
city_risk_score          float64
vehicle_make                 str
vehicle_model                str
variant                      str
segment                      str
fuel_type                    str
colour                       str
manufacturing_year         int64
vehicle_age_years          int64
engine_cc                  int64
idv                        int64
ncb_percent                int64
claim_history_count        int64
policy_type                  str
usage_type                   str
num_addons                 int64
addons_list                  str
od_premium_before_ncb    float64
ncb_discount_amount      float64
tp_premium                 int64
addon_premium            float64
gst_amount               float64
annual_premium             int64
addons_list_clean         object
dtype: object

In [15]:
drop_cols = [
    'record_id', 'annual_premium', 'addons_list', 'addons_list_clean',
    'od_premium_before_ncb', 'ncb_discount_amount', 'tp_premium', 
    'addon_premium', 'gst_amount'
]
bike_final = bike.drop(columns=drop_cols, errors='ignore')

In [16]:
bike.dtypes

record_id                                 str
customer_age                            int64
city                                      str
state                                     str
city_tier                               int64
city_risk_score                       float64
vehicle_make                              str
vehicle_model                             str
variant                                   str
segment                                   str
fuel_type                                 str
colour                                    str
manufacturing_year                      int64
vehicle_age_years                       int64
engine_cc                               int64
idv                                     int64
ncb_percent                             int64
claim_history_count                     int64
policy_type                               str
usage_type                                str
num_addons                              int64
addons_list                               str
od_premium_before_ncb                 float64
ncb_discount_amount                   float64
tp_premium                              int64
addon_premium                         float64
gst_amount                            float64
annual_premium                          int64
addons_list_clean                      object
addon_consumables_cover      Sparse[int64, 0]
addon_engine_protection      Sparse[int64, 0]
addon_pillion_rider_cover    Sparse[int64, 0]
addon_return_to_invoice      Sparse[int64, 0]
addon_roadside_assistance    Sparse[int64, 0]
addon_unknown                Sparse[int64, 0]
addon_zero_depreciation      Sparse[int64, 0]
dtype: object

In [17]:
bike.columns

Index(['record_id', 'customer_age', 'city', 'state', 'city_tier',
       'city_risk_score', 'vehicle_make', 'vehicle_model', 'variant',
       'segment', 'fuel_type', 'colour', 'manufacturing_year',
       'vehicle_age_years', 'engine_cc', 'idv', 'ncb_percent',
       'claim_history_count', 'policy_type', 'usage_type', 'num_addons',
       'addons_list', 'od_premium_before_ncb', 'ncb_discount_amount',
       'tp_premium', 'addon_premium', 'gst_amount', 'annual_premium',
       'addons_list_clean', 'addon_consumables_cover',
       'addon_engine_protection', 'addon_pillion_rider_cover',
       'addon_return_to_invoice', 'addon_roadside_assistance', 'addon_unknown',
       'addon_zero_depreciation'],
      dtype='str')

In [18]:
numeric_bike = [
    'customer_age', 'city_tier', 'city_risk_score', 'manufacturing_year', 
    'vehicle_age_years', 'engine_cc', 'idv', 'ncb_percent', 
    'claim_history_count', 'num_addons','addon_consumables_cover', 'addon_engine_protection',
       'addon_pillion_rider_cover', 'addon_return_to_invoice',
       'addon_roadside_assistance', 'addon_unknown',
       'addon_zero_depreciation'
]

# 2. CORRECT CATEGORICAL LIST
category_bike = [
    'vehicle_make', 'vehicle_model','segment', 
    'fuel_type','policy_type', 
    'city', 'state','variant'
]

In [19]:
df_bike

,record_id,customer_age,city,state,city_tier,city_risk_score,vehicle_make,vehicle_model,variant,segment,...,usage_type,num_addons,addons_list,od_premium_before_ncb,ncb_discount_amount,tp_premium,addon_premium,gst_amount,annual_premium,addons_list_clean
0,c007100c,60,Rajahmundry,Andhra Pradesh,3,0.88,Royal Enfield,Bullet 500,STD,retro,...,Personal,0,Unknown,3861.87,0.00,2804,0.00,1295.85,8338,[Unknown]
1,01557b26,21,Indore,Madhya Pradesh,2,1.15,Yamaha,Fascino 125,ABS,scooter,...,Personal,0,Unknown,1139.68,512.86,714,0.00,151.65,1035,[Unknown]
2,656c8f49,19,Patna,Bihar,2,1.20,Suzuki,Gixxer 150,Drum,sport,...,Personal,3,"Roadside Assistance, Consumables Cover, Return...",2464.40,862.54,1366,3317.48,290.14,1829,"[Roadside Assistance, Consumables Cover, Retur..."
3,506ccfca,20,Muzaffarpur,Bihar,3,0.88,Bounce,Infinity E1,ABS,ev_scooter,...,Personal,0,Unknown,702.02,315.91,687,0.00,227.93,1536,[Unknown]
4,3d46cd32,19,Karnal,Haryana,3,0.90,Honda,CB Hornet 2.0,Limited Edition,sport,...,Personal,0,Unknown,2164.95,974.23,1366,0.00,252.91,1731,[Unknown]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,3f453740,45,Ahmedabad,Gujarat,1,1.30,Ola Electric,S1 X,Disc,ev_scooter,...,Personal,1,Zero Depreciation,1331.25,465.94,687,991.76,457.93,2852,[Zero Depreciation]
149996,7afc65c4,20,Hisar,Haryana,3,0.90,Honda,CB Hornet 2.0,Limited Edition,sport,...,Commercial,2,"Return to Invoice, Zero Depreciation",2550.70,0.00,1366,1711.77,1195.49,7783,"[Return to Invoice, Zero Depreciation]"
149997,a4e45542,65,Moradabad,Uttar Pradesh,2,1.10,Royal Enfield,Thunderbird 350X,Sport,cruiser,...,Personal,1,Return to Invoice,4617.64,0.00,1366,453.01,265.55,1687,[Return to Invoice]
149998,474628c4,63,Bengaluru,Karnataka,1,1.45,TVS,Apache RTR 160 4V,STD,sport,...,Personal,2,"Return to Invoice, Consumables Cover",6151.40,0.00,1366,2015.13,1948.79,13367,"[Return to Invoice, Consumables Cover]"
149999,77a12382,29,Warangal,Telangana,2,1.05,Ampere,Magnus EX,Bluetooth,ev_scooter,...,Commercial,0,Unknown,1685.66,337.13,687,0.00,242.73,1629,[Unknown]

In [20]:
df_bike.drop('addons_list_clean',axis=1)

,record_id,customer_age,city,state,city_tier,city_risk_score,vehicle_make,vehicle_model,variant,segment,...,policy_type,usage_type,num_addons,addons_list,od_premium_before_ncb,ncb_discount_amount,tp_premium,addon_premium,gst_amount,annual_premium
0,c007100c,60,Rajahmundry,Andhra Pradesh,3,0.88,Royal Enfield,Bullet 500,STD,retro,...,Comprehensive,Personal,0,Unknown,3861.87,0.00,2804,0.00,1295.85,8338
1,01557b26,21,Indore,Madhya Pradesh,2,1.15,Yamaha,Fascino 125,ABS,scooter,...,Third Party,Personal,0,Unknown,1139.68,512.86,714,0.00,151.65,1035
2,656c8f49,19,Patna,Bihar,2,1.20,Suzuki,Gixxer 150,Drum,sport,...,Third Party,Personal,3,"Roadside Assistance, Consumables Cover, Return...",2464.40,862.54,1366,3317.48,290.14,1829
3,506ccfca,20,Muzaffarpur,Bihar,3,0.88,Bounce,Infinity E1,ABS,ev_scooter,...,Comprehensive,Personal,0,Unknown,702.02,315.91,687,0.00,227.93,1536
4,3d46cd32,19,Karnal,Haryana,3,0.90,Honda,CB Hornet 2.0,Limited Edition,sport,...,Own Damage,Personal,0,Unknown,2164.95,974.23,1366,0.00,252.91,1731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,3f453740,45,Ahmedabad,Gujarat,1,1.30,Ola Electric,S1 X,Disc,ev_scooter,...,Comprehensive,Personal,1,Zero Depreciation,1331.25,465.94,687,991.76,457.93,2852
149996,7afc65c4,20,Hisar,Haryana,3,0.90,Honda,CB Hornet 2.0,Limited Edition,sport,...,Comprehensive,Commercial,2,"Return to Invoice, Zero Depreciation",2550.70,0.00,1366,1711.77,1195.49,7783
149997,a4e45542,65,Moradabad,Uttar Pradesh,2,1.10,Royal Enfield,Thunderbird 350X,Sport,cruiser,...,Third Party,Personal,1,Return to Invoice,4617.64,0.00,1366,453.01,265.55,1687
149998,474628c4,63,Bengaluru,Karnataka,1,1.45,TVS,Apache RTR 160 4V,STD,sport,...,Comprehensive,Personal,2,"Return to Invoice, Consumables Cover",6151.40,0.00,1366,2015.13,1948.79,13367
149999,77a12382,29,Warangal,Telangana,2,1.05,Ampere,Magnus EX,Bluetooth,ev_scooter,...,Own Damage,Commercial,0,Unknown,1685.66,337.13,687,0.00,242.73,1629

In [21]:
numeric_corr2 = bike[numeric_bike].corrwith(df_bike['annual_premium']).abs()

# Sort and display the results cleanly
numeric_ranking2 = pd.DataFrame({
    'Numeric Feature': numeric_corr2.index,
    'Correlation Score': numeric_corr2.values
}).sort_values(by='Correlation Score', ascending=False)

print("🏆 Numeric Columns Ranked by Relationship to Premium:")
print(numeric_ranking2.to_string(index=False))

🏆 Numeric Columns Ranked by Relationship to Premium:
          Numeric Feature  Correlation Score
                      idv           0.738509
                engine_cc           0.683370
        vehicle_age_years           0.101087
       manufacturing_year           0.101087
              ncb_percent           0.097102
          city_risk_score           0.066341
               num_addons           0.064430
                city_tier           0.061347
            addon_unknown           0.050833
  addon_zero_depreciation           0.030538
  addon_engine_protection           0.029394
addon_pillion_rider_cover           0.028392
      claim_history_count           0.027873
addon_roadside_assistance           0.026701
  addon_return_to_invoice           0.026295
  addon_consumables_cover           0.024030
             customer_age           0.006547

In [22]:
from sklearn.feature_selection import mutual_info_regression

# 1. Temporarily fill missing text values for calculation
X_cat_bike = bike[category_bike]

# 2. Convert text words into numerical codes so the MI algorithm can read them
for col in category_bike:
    X_cat_bike[col] = X_cat_bike[col].astype('category').cat.codes

# 3. Calculate Mutual Information scores
mi_scores = mutual_info_regression(X_cat_bike, df_bike['annual_premium'], random_state=42)

# 4. Sort and display the rankings
cat_ranking = pd.DataFrame({
    'Categorical Feature': category_bike,
    'Mutual Info Score': mi_scores
}).sort_values(by='Mutual Info Score', ascending=False)

print("\n🏆 Categorical Columns Ranked by Relationship to Premium:")
print(cat_ranking.to_string(index=False))

🏆 Categorical Columns Ranked by Relationship to Premium:
Categorical Feature  Mutual Info Score
      vehicle_model           0.668249
        policy_type           0.449720
            segment           0.429750
       vehicle_make           0.347425
          fuel_type           0.158901
               city           0.003773
              state           0.001504
            variant           0.000000

In [23]:
X_bike = bike[numeric_bike + category_bike]
Y_bike = df_bike['annual_premium']

In [24]:
X_bike

,customer_age,city_tier,city_risk_score,manufacturing_year,vehicle_age_years,engine_cc,idv,ncb_percent,claim_history_count,num_addons,...,addon_unknown,addon_zero_depreciation,vehicle_make,vehicle_model,segment,fuel_type,policy_type,city,state,variant
0,60,3,0.88,2018,7,499,106815,0,0,0,...,1,0,Royal Enfield,Bullet 500,retro,Petrol,Comprehensive,Rajahmundry,Andhra Pradesh,STD
1,21,2,1.15,2012,13,125,22704,45,0,0,...,1,0,Yamaha,Fascino 125,scooter,Petrol,Third Party,Indore,Madhya Pradesh,ABS
2,19,2,1.20,2011,14,155,36271,35,0,3,...,0,0,Suzuki,Gixxer 150,sport,Petrol,Third Party,Patna,Bihar,Drum
3,20,3,0.88,2011,14,0,21416,45,0,0,...,1,0,Bounce,Infinity E1,ev_scooter,Electric,Comprehensive,Muzaffarpur,Bihar,ABS
4,19,3,0.90,2007,18,184,38836,45,0,0,...,1,0,Honda,CB Hornet 2.0,sport,Petrol,Own Damage,Karnal,Haryana,Limited Edition
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,45,1,1.30,2011,14,0,27491,35,0,1,...,0,1,Ola Electric,S1 X,ev_scooter,Electric,Comprehensive,Ahmedabad,Gujarat,Disc
149996,20,3,0.90,2011,14,184,40044,0,0,2,...,0,1,Honda,CB Hornet 2.0,sport,Petrol,Comprehensive,Hisar,Haryana,Limited Edition
149997,65,2,1.10,2019,6,346,99123,0,0,1,...,0,0,Royal Enfield,Thunderbird 350X,cruiser,Petrol,Third Party,Moradabad,Uttar Pradesh,Sport
149998,63,1,1.45,2023,2,159,104337,0,1,2,...,0,0,TVS,Apache RTR 160 4V,sport,Petrol,Comprehensive,Bengaluru,Karnataka,STD
149999,29,2,1.05,2018,7,0,41263,20,0,0,...,1,0,Ampere,Magnus EX,ev_scooter,Electric,Own Damage,Warangal,Telangana,Bluetooth

In [25]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, TargetEncoder, StandardScaler,LabelEncoder,OrdinalEncoder
from xgboost import XGBRegressor

In [26]:
X_btrain, X_btest, y_btrain, y_btest = train_test_split(X_bike, Y_bike, test_size=0.2, random_state=42)

In [27]:
preprocessor2 = ColumnTransformer(
    transformers=[
        # Encode ALL text categories safely with zero memory overhead
        ('all_categorical_encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), 
         ['segment', 'fuel_type', 'policy_type', 'city', 'state', 'vehicle_make', 'vehicle_model','variant']),
        
        # Scale continuous numbers
        ('numerical_scaler', StandardScaler(), 
         ['customer_age', 'city_tier', 'city_risk_score', 'vehicle_age_years', 
          'engine_cc', 'idv', 'ncb_percent', 'claim_history_count', 'num_addons','manufacturing_year']),
    ],
    remainder='passthrough',
    sparse_threshold=0.0
)

In [28]:
X_btrain_final = preprocessor2.fit_transform(X_btrain, y_btrain)
X_btest_final = preprocessor2.transform(X_btest)

In [29]:
modelb = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    tree_method='hist', # Super-fast optimization for heavy datasets
    random_state=42,
    n_jobs=-1
)

modelb.fit(X_btrain_final, y_btrain)
print("🏆 Model training complete!")

🏆 Model training complete!

In [30]:
print(f"Final Model Train R² Score: {modelb.score(X_btrain_final, y_btrain):.4f}")
print(f"Final Model Test R² Score: {modelb.score(X_btest_final, y_btest):.4f}")

Final Model Train R² Score: 0.9871
Final Model Test R² Score: 0.9753

In [ ]:
import joblib
import os

os.makedirs('model_artifacts', exist_ok=True)


joblib.dump(preprocessor2, 'ml/saved_models/bike_insurance_preprocessor.pkl')
joblib.dump(modelb, 'ml/saved_models/bike_insurance_xgboost_model.pkl')

print("💾 Production files successfully saved in 'model_artifacts/' folder!")

💾 Production files successfully saved in 'model_artifacts/' folder!

In [61]:
df_health

,record_id,plan_name,plan_category,age,gender,num_members,city_tier,state,bmi_category,smoke,...,deductible,num_addons,addons_list,has_maternity,has_opd,policy_tenure,prev_insurer,annual_premium,gst_amount,total_premium
0,AHQ000000,Family Floater Standard,Family,23,Male,4,2,Punjab,Normal,0,...,25000,1,dental_vision,0,0,2,Bajaj Allianz,78300.0,14094.0,92394.0
1,AHQ000001,Critical Illness,Specialty,43,Female,1,3,Delhi,Overweight,0,...,0,0,NaN,0,0,1,Niva Bupa,53500.0,9630.0,63130.0
2,AHQ000002,Family Floater Premium,Family,20,Female,5,1,Madhya Pradesh,Normal,0,...,0,0,NaN,0,0,2,SBI Health,181400.0,32652.0,214052.0
3,AHQ000003,Senior Citizen,Senior,61,Female,2,1,Haryana,Overweight,0,...,5000,3,maternity|critical_illness_rider|international...,1,0,1,Care Health,147000.0,26460.0,173460.0
4,AHQ000004,Family Floater Standard,Family,43,Male,2,3,Kerala,Overweight,0,...,0,1,personal_accident,0,0,1,SBI Health,37200.0,6696.0,43896.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,AHQ019995,Individual Standard,Individual,22,Female,2,1,Delhi,Normal,0,...,0,2,personal_accident|maternity,1,0,1,Bajaj Allianz,34200.0,6156.0,40356.0
19996,AHQ019996,Individual Premium,Individual,34,Male,2,3,Kerala,Normal,0,...,10000,1,maternity,1,0,1,ACKO,53100.0,9558.0,62658.0
19997,AHQ019997,Senior Citizen,Senior,63,Female,5,2,Rajasthan,Normal,0,...,0,2,critical_illness_rider|personal_accident,0,0,1,United India,208100.0,37458.0,245558.0
19998,AHQ019998,Individual Standard,Individual,58,Male,2,3,Haryana,Overweight,0,...,5000,1,maternity,1,0,2,Bajaj Allianz,84600.0,15228.0,99828.0
19999,AHQ019999,Individual Premium,Individual,48,Female,1,3,Maharashtra,Overweight,0,...,0,1,hospital_cash,0,0,1,Care Health,23600.0,4248.0,27848.0

In [62]:
df_health.columns

Index(['record_id', 'plan_name', 'plan_category', 'age', 'gender',
       'num_members', 'city_tier', 'state', 'bmi_category', 'smoke',
       'has_pre_existing', 'annual_checkup', 'ncb_years', 'sum_insured',
       'deductible', 'num_addons', 'addons_list', 'has_maternity', 'has_opd',
       'policy_tenure', 'prev_insurer', 'annual_premium', 'gst_amount',
       'total_premium'],
      dtype='str')

In [63]:
df_health.dtypes

record_id               str
plan_name               str
plan_category           str
age                   int64
gender                  str
num_members           int64
city_tier             int64
state                   str
bmi_category            str
smoke                 int64
has_pre_existing      int64
annual_checkup        int64
ncb_years             int64
sum_insured           int64
deductible            int64
num_addons            int64
addons_list             str
has_maternity         int64
has_opd               int64
policy_tenure         int64
prev_insurer            str
annual_premium      float64
gst_amount          float64
total_premium       float64
dtype: object

In [64]:
df_health.duplicated().sum()

np.int64(0)

In [65]:
df_health.describe()

,age,num_members,city_tier,smoke,has_pre_existing,annual_checkup,ncb_years,sum_insured,deductible,num_addons,has_maternity,has_opd,policy_tenure,annual_premium,gst_amount,total_premium
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,2.000000e+04,20000.00000,2.000000e+04
mean,45.978550,2.312700,1.902200,0.153350,0.266650,0.451800,1.495700,8.944425e+05,6388.500000,1.995350,0.286900,0.288450,1.540400,1.108002e+05,19944.03420,1.307442e+05
std,16.416558,1.266925,0.768157,0.360334,0.442219,0.497684,1.473258,1.022656e+06,11416.264026,1.408271,0.452326,0.453053,0.730681,1.065603e+05,19180.85273,1.257411e+05
min,18.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,3.000000e+05,0.000000,0.000000,0.000000,0.000000,1.000000,3.800000e+03,684.00000,4.484000e+03
25%,32.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,3.000000e+05,0.000000,1.000000,0.000000,0.000000,1.000000,3.970000e+04,7146.00000,4.684600e+04
50%,46.000000,2.000000,2.000000,0.000000,0.000000,0.000000,1.000000,5.000000e+05,0.000000,2.000000,0.000000,0.000000,1.000000,7.690000e+04,13842.00000,9.074200e+04
75%,60.000000,3.000000,3.000000,0.000000,1.000000,1.000000,3.000000,1.000000e+06,10000.000000,3.000000,1.000000,1.000000,2.000000,1.427000e+05,25686.00000,1.683860e+05
max,74.000000,5.000000,3.000000,1.000000,1.000000,1.000000,5.000000,1.000000e+07,50000.000000,4.000000,1.000000,1.000000,3.000000,1.090800e+06,196344.00000,1.287144e+06

In [66]:
df_health.isnull().sum()

record_id              0
plan_name              0
plan_category          0
age                    0
gender                 0
num_members            0
city_tier              0
state                  0
bmi_category           0
smoke                  0
has_pre_existing       0
annual_checkup         0
ncb_years              0
sum_insured            0
deductible             0
num_addons             0
addons_list         3967
has_maternity          0
has_opd                0
policy_tenure          0
prev_insurer           0
annual_premium         0
gst_amount             0
total_premium          0
dtype: int64

In [67]:
df_health['addons_list'] = df_health['addons_list'].fillna('Unknown')

In [68]:
df_health.isnull().sum()

record_id           0
plan_name           0
plan_category       0
age                 0
gender              0
num_members         0
city_tier           0
state               0
bmi_category        0
smoke               0
has_pre_existing    0
annual_checkup      0
ncb_years           0
sum_insured         0
deductible          0
num_addons          0
addons_list         0
has_maternity       0
has_opd             0
policy_tenure       0
prev_insurer        0
annual_premium      0
gst_amount          0
total_premium       0
dtype: int64

In [69]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer

# 1. Clean the text and convert comma-separated strings into clean Python lists
def clean_addon_string_health(text):
    # Handle NaN or empty string inputs gracefully
    if pd.isna(text) or text == '':
        return []
    # Split by comma and strip out accidental whitespace around names
    return [addon.strip() for addon in text.split('|') if addon.strip()]

# Apply the text cleaning function to your column
df_health['addons_list_clean'] = df_health['addons_list'].apply(clean_addon_string_health)

# 2. Initialize the MultiLabelBinarizer with Sparse Output enabled
# This completely prevents memory crashes by ignoring zero values
mlb = MultiLabelBinarizer(sparse_output=True)

# 3. Fit and transform the clean lists into a compressed matrix
X_addons_health_sparse = mlb.fit_transform(df_health['addons_list_clean'])

# 4. Verify your results
print(f"Compressed Sparse Matrix Shape: {X_addons_health_sparse.shape}")
print(f"Detected Unique Addon Columns: {mlb.classes_}")

Compressed Sparse Matrix Shape: (20000, 8)
Detected Unique Addon Columns: ['Unknown' 'critical_illness_rider' 'dental_vision' 'hospital_cash'
 'international_cover' 'maternity' 'opd_cover' 'personal_accident']

In [70]:
addons_h_df = pd.DataFrame.sparse.from_spmatrix(
    X_addons_health_sparse, 
    columns=[f"addon_{name.lower().replace(' ', '_')}" for name in mlb.classes_]
)

# 2. Reset indices to ensure perfect horizontal alignment
df_health = df_health.reset_index(drop=True)
addons_h_df = addons_h_df.reset_index(drop=True)

# 3. Glue them together side-by-side
health = pd.concat([df_health, addons_h_df], axis=1)

In [71]:
health

,record_id,plan_name,plan_category,age,gender,num_members,city_tier,state,bmi_category,smoke,...,total_premium,addons_list_clean,addon_unknown,addon_critical_illness_rider,addon_dental_vision,addon_hospital_cash,addon_international_cover,addon_maternity,addon_opd_cover,addon_personal_accident
0,AHQ000000,Family Floater Standard,Family,23,Male,4,2,Punjab,Normal,0,...,92394.0,[dental_vision],0,0,1,0,0,0,0,0
1,AHQ000001,Critical Illness,Specialty,43,Female,1,3,Delhi,Overweight,0,...,63130.0,[Unknown],1,0,0,0,0,0,0,0
2,AHQ000002,Family Floater Premium,Family,20,Female,5,1,Madhya Pradesh,Normal,0,...,214052.0,[Unknown],1,0,0,0,0,0,0,0
3,AHQ000003,Senior Citizen,Senior,61,Female,2,1,Haryana,Overweight,0,...,173460.0,"[maternity, critical_illness_rider, internatio...",0,1,0,0,1,1,0,0
4,AHQ000004,Family Floater Standard,Family,43,Male,2,3,Kerala,Overweight,0,...,43896.0,[personal_accident],0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,AHQ019995,Individual Standard,Individual,22,Female,2,1,Delhi,Normal,0,...,40356.0,"[personal_accident, maternity]",0,0,0,0,0,1,0,1
19996,AHQ019996,Individual Premium,Individual,34,Male,2,3,Kerala,Normal,0,...,62658.0,[maternity],0,0,0,0,0,1,0,0
19997,AHQ019997,Senior Citizen,Senior,63,Female,5,2,Rajasthan,Normal,0,...,245558.0,"[critical_illness_rider, personal_accident]",0,1,0,0,0,0,0,1
19998,AHQ019998,Individual Standard,Individual,58,Male,2,3,Haryana,Overweight,0,...,99828.0,[maternity],0,0,0,0,0,1,0,0
19999,AHQ019999,Individual Premium,Individual,48,Female,1,3,Maharashtra,Overweight,0,...,27848.0,[hospital_cash],0,0,0,1,0,0,0,0

In [72]:
health.columns

Index(['record_id', 'plan_name', 'plan_category', 'age', 'gender',
       'num_members', 'city_tier', 'state', 'bmi_category', 'smoke',
       'has_pre_existing', 'annual_checkup', 'ncb_years', 'sum_insured',
       'deductible', 'num_addons', 'addons_list', 'has_maternity', 'has_opd',
       'policy_tenure', 'prev_insurer', 'annual_premium', 'gst_amount',
       'total_premium', 'addons_list_clean', 'addon_unknown',
       'addon_critical_illness_rider', 'addon_dental_vision',
       'addon_hospital_cash', 'addon_international_cover', 'addon_maternity',
       'addon_opd_cover', 'addon_personal_accident'],
      dtype='str')

In [73]:
health_num = ['age','num_members', 'city_tier', 'smoke',
       'has_pre_existing', 'annual_checkup', 'ncb_years', 'sum_insured',
       'deductible', 'num_addons','has_maternity', 'has_opd','addon_critical_illness_rider', 'addon_dental_vision',
       'addon_hospital_cash', 'addon_international_cover', 'addon_maternity',
       'addon_opd_cover', 'addon_personal_accident',
       'policy_tenure']

health_cat= ['plan_name', 'plan_category','gender','state', 'bmi_category']

target = ['total_premium']

In [74]:
health_final=health[health_num + health_cat]
health_tar=  df_health['total_premium']

In [75]:
numeric_corr3 = health_final[health_num].corrwith(df_health['total_premium']).abs()

# Sort and display the results cleanly
numeric_ranking3 = pd.DataFrame({
    'Numeric Feature': numeric_corr3.index,
    'Correlation Score': numeric_corr3.values
}).sort_values(by='Correlation Score', ascending=False)

print("🏆 Numeric Columns Ranked by Relationship to Premium:")
print(numeric_ranking3.to_string(index=False))

🏆 Numeric Columns Ranked by Relationship to Premium:
             Numeric Feature  Correlation Score
                         age           0.489756
               policy_tenure           0.451257
                 num_members           0.326541
            has_pre_existing           0.177437
                 sum_insured           0.157006
                   city_tier           0.098690
                       smoke           0.092255
                   ncb_years           0.081516
                  num_addons           0.077582
                  deductible           0.054327
     addon_personal_accident           0.045479
         addon_dental_vision           0.039449
   addon_international_cover           0.034996
addon_critical_illness_rider           0.033380
               has_maternity           0.032426
             addon_maternity           0.032426
             addon_opd_cover           0.029059
                     has_opd           0.029059
         addon_hospital_cash           0.027290
              annual_checkup           0.015607

In [76]:
from sklearn.feature_selection import mutual_info_regression

# 1. Temporarily fill missing text values for calculation
X_cat_h_temp = df_health[health_cat].fillna('Unknown')

# 2. Convert text words into numerical codes so the MI algorithm can read them
for col in health_cat:
    X_cat_h_temp[col] = X_cat_h_temp[col].astype('category').cat.codes

# 3. Calculate Mutual Information scores
mi_scores = mutual_info_regression(X_cat_h_temp, df_health['total_premium'], random_state=42)

# 4. Sort and display the rankings
cat_ranking = pd.DataFrame({
    'Categorical Feature': health_cat,
    'Mutual Info Score': mi_scores
}).sort_values(by='Mutual Info Score', ascending=False)

print("\n🏆 Categorical Columns Ranked by Relationship to Premium:")
print(cat_ranking.to_string(index=False))

🏆 Categorical Columns Ranked by Relationship to Premium:
Categorical Feature  Mutual Info Score
          plan_name           0.386192
      plan_category           0.226140
             gender           0.000145
              state           0.000000
       bmi_category           0.000000

In [77]:
df_health = health[health_num + health_cat]

In [78]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

preprocessor3 = ColumnTransformer(
    transformers=[
        # 1. FIXED: All text categories AND lifestyle/benefit flags grouped together
        ('all_categorical_encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), 
         ['plan_name', 'plan_category', 'gender', 'state', 'bmi_category']),
        
        # 2. FIXED: Scaler holds ONLY true continuous metrics and counts
        ('numerical_scaler', StandardScaler(), 
         ['age', 'num_members', 'city_tier', 'ncb_years', 'sum_insured', 
          'deductible', 'num_addons', 'policy_tenure',
          'smoke', 'has_pre_existing', 'annual_checkup', 'has_maternity', 'has_opd']),
    ],
    # 'passthrough' will seamlessly handle your sparse addon features out of the box!
    remainder='passthrough',
    sparse_threshold=0.0
)

In [79]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, TargetEncoder, StandardScaler,LabelEncoder,OrdinalEncoder
from xgboost import XGBRegressor

In [80]:
X_htrain, X_htest, y_htrain, y_htest = train_test_split(health_final, health_tar, test_size=0.2, random_state=42)

In [81]:
X_htrain_final = preprocessor3.fit_transform(X_htrain, y_htrain)
X_htest_final = preprocessor3.transform(X_htest)

In [82]:
modelh = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    tree_method='hist', # Super-fast optimization for heavy datasets
    random_state=42,
    n_jobs=-1
)

modelh.fit(X_htrain_final, y_htrain)
print("🏆 Model training complete!")

🏆 Model training complete!

In [83]:
print(f"Final Model Train R² Score: {modelh.score(X_htrain_final, y_htrain):.4f}")
print(f"Final Model Test R² Score: {modelh.score(X_htest_final, y_htest):.4f}")

Final Model Train R² Score: 0.9937
Final Model Test R² Score: 0.9786

In [84]:
import joblib
import os

os.makedirs('model_artifacts', exist_ok=True)


joblib.dump(preprocessor3, 'ml/saved_models/health_insurance_preprocessor.pkl')
joblib.dump(modelh, 'ml/saved_models/health_insurance_xgboost_model.pkl')

print("💾 Production files successfully saved in 'model_artifacts/' folder!")

💾 Production files successfully saved in 'model_artifacts/' folder!